# Generated by Django 2.1.7 on 2019-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190112_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_public',
            field=models.BooleanField(default=True),
        ),
    ]
