# Generated by Django 2.1.4 on 2019-01-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newsletter', '0002_auto_20190102_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('-pk',)},
        ),
    ]
