# Generated by Django 2.1.4 on 2019-01-05 20:01

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190103_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_image',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
