# Generated by Django 2.1.5 on 2019-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summary',
            field=models.TextField(default='something'),
        ),
    ]
