# Generated by Django 2.1.4 on 2019-01-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190108_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='articles_pictures/%Y/%m/%d/', verbose_name='thumbnail image'),
        ),
    ]
