# Generated by Django 2.1.4 on 2019-01-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1),
        ),
    ]
