# Generated by Django 2.1.7 on 2019-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20190307_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='receive_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='receive_email',
            field=models.BooleanField(default=True),
        ),
    ]
