# Generated by Django 2.1.7 on 2019-02-27 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0003_auto_20190130_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='flag',
            field=models.ManyToManyField(related_name='flag_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='flag',
            field=models.ManyToManyField(related_name='flag_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
