# Generated by Django 2.1.7 on 2019-03-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20190308_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='receive_email',
            field=models.BooleanField(default=False),
        ),
    ]
