# Generated by Django 2.1.7 on 2019-03-02 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20190227_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='flag',
            field=models.ManyToManyField(blank=True, related_name='flag_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
