# Generated by Django 2.1.4 on 2019-01-08 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0004_auto_20190108_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='close_question',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='question_close_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
