# Generated by Django 2.1.7 on 2019-03-08 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0005_auto_20190308_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='receive_email',
        ),
        migrations.AddField(
            model_name='question',
            name='other_user_receive_email',
            field=models.ManyToManyField(blank=True, related_name='answer_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
