# Generated by Django 2.1.4 on 2019-01-08 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_question_close_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='close_question',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_close_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
