# Generated by Django 2.1.7 on 2019-03-03 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0006_auto_20190303_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='close_question',
        ),
        migrations.AddField(
            model_name='question',
            name='close_question_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='close_question_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_close_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
