# Generated by Django 2.1.7 on 2019-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_auto_20190303_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='close_question_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
