# Generated by Django 2.1 on 2018-12-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180729_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
