# Generated by Django 2.1 on 2018-12-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181206_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_answered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
