# Generated by Django 2.1 on 2018-12-27 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181213_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
