# Generated by Django 2.1 on 2018-12-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181228_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_answered',
        ),
    ]
