# Generated by Django 2.1.2 on 2018-12-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_question_question_answered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-pk',)},
        ),
    ]
