# Generated by Django 2.1.7 on 2019-03-07 04:48

import assignment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('topic', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('assignment_file', models.FileField(upload_to=assignment.models.assignment_upload_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment_views', models.PositiveIntegerField(default=0)),
                ('draft', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assignment_file', models.FileField(upload_to=assignment.models.student_assignment_upload_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
