# Generated by Django 2.1.4 on 2019-01-11 12:54

import assignment.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('topic', models.CharField(max_length=240)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('assignment_file', models.FileField(upload_to=assignment.models.assignment_upload_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment_views', models.PositiveIntegerField(default=0)),
                ('draft', models.BooleanField(blank=True, default=False, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
