# Generated by Django 2.1.4 on 2019-01-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='draft',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
