# Generated by Django 2.1.7 on 2019-03-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20190228_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('-timestamp', '-pk')},
        ),
    ]
