# Generated by Django 2.1.7 on 2019-03-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20190307_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
    ]
